# docker-compose.yml

version: '3.8'
services:

  postgres:
    container_name: postgres
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=lastmorn
      - POSTGRES_PASSWORD=lastmorn
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"

volumes:
  postgres:
  pgadmin: